version: '3.8'

services:
  ci-test:
    image: app-local-builder
    build:
      context: go
      dockerfile: cmd/api/Dockerfile
      target: builder
    command: >
      /bin/bash -c "go test -json -race -covermode=atomic
      -coverprofile=tmp/coverage.out ./... > tmp/report.json"
    volumes:
      - ./tmp:/workspace/tmp
    networks:
      - private

networks:
  private: