version: '3.8'

services:
  ci-test:
    image: api-local-builder
    build:
      context: go
      dockerfile: cmd/api/Dockerfile
      target: builder
    command: >
      /bin/bash -c "go test -json -race -covermode=atomic
      -coverprofile=testoutput/coverage.out ./... > testoutput/report.json"
    volumes:
      - ./go/testoutput:/workspace/testoutput
    networks:
      - private