name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run CI tests
      run: make ci-test
    - name: Archive test run report
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-report
        path: testoutput/report.json
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: testoutput/coverage.out
    - name: Build production image
      run: make build-api-docker-image
